# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gohome < Formula
  desc ""
  homepage ""
  version "0.0.4"

  on_macos do
    on_intel do
      url "https://github.com/EBNull/gohome/releases/download/v0.0.4/gohome_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{GitHub::API.credentials}"
        ]
      sha256 "bf4deef9553b45fad7bfd93f90ff5b9b2fb256ac16dcff1a59ddd28da9a258e6"

      def install
        bin.install "gohome"
      end
    end
    on_arm do
      url "https://github.com/EBNull/gohome/releases/download/v0.0.4/gohome_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{GitHub::API.credentials}"
        ]
      sha256 "2ae0eb4f30bebcba9a70b861da4e7339150e2eec7c0d0249aa5a1f61e6e77d24"

      def install
        bin.install "gohome"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/EBNull/gohome/releases/download/v0.0.4/gohome_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{GitHub::API.credentials}"
          ]
        sha256 "bf3c05a1ef2e1f6f62abea3619369ef5efb766ca4435bb06d6bdcd4d39b6b79c"

        def install
          bin.install "gohome"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/EBNull/gohome/releases/download/v0.0.4/gohome_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{GitHub::API.credentials}"
          ]
        sha256 "53debf5c3e9e00895e15f48c4aa4b2e4b022481f2d693a5e81054ebd7b7c4780"

        def install
          bin.install "gohome"
        end
      end
    end
  end

  service do
    run [opt_bin/"gohome"]
    require_root true
    working_dir HOMEBREW_PREFIX
  end
end
