# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gohome < Formula
  desc "go/links daemon for your local machine"
  homepage "https://github.com/EBNull/gohome"
  version "0.0.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/EBNull/gohome/releases/download/v0.0.5/gohome_Darwin_x86_64.tar.gz"
      sha256 "040f13346cb9e33ae9def4bfc37b088e2f93094a8e9102c083dec88be32b1f71"

      def install
        bin.install "gohome"
      end
    end
    on_arm do
      url "https://github.com/EBNull/gohome/releases/download/v0.0.5/gohome_Darwin_arm64.tar.gz"
      sha256 "c6d07762da441d6b86b43ebfb1ee7e62e9ef1fff36081a62146666d00c97422c"

      def install
        bin.install "gohome"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/EBNull/gohome/releases/download/v0.0.5/gohome_Linux_x86_64.tar.gz"
        sha256 "7d3aeca50576e06a412d9dbfaa79a839fe87891106ff1de5e8a1a120d88183a0"

        def install
          bin.install "gohome"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/EBNull/gohome/releases/download/v0.0.5/gohome_Linux_arm64.tar.gz"
        sha256 "a3166afb34509ceac4274398027f649e8640aef5d7fed6d8432318f93d4a9ea4"

        def install
          bin.install "gohome"
        end
      end
    end
  end

  service do
    run [opt_bin/"gohome"]
    require_root true
    working_dir HOMEBREW_PREFIX
  end

  test do
    system "#{bin}/gohome --version"
  end
end
